version: "3.8"
services:
  application:
    container_name: consumption-tracker
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5433:${POSTGRES_PORT}"
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}

volumes:
  data: {}
